export const SET_OTP_EMAIL = 'SET_OTP_EMAIL';
export const SET_USER='SET_USER';
export const SET_RESTAURANTS = 'SET_RESTAURANTS';
export const SET_FETCHED_PRODUCTS = 'SET_PRODUCTS';
export const SET_MODAL_DETAILS = 'SET_MODAL_DETAILS';