export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER'; 
export const INCREMENT_REDBUTTON = ' INCREMENT_REDBUTTON';
export const SET_USER='SET_USER';