const signin = {
	en: {
		emailPlaceholder: 'Email',
		passwordPlaceholder: 'Password',
		forgotpassword: 'Forgot password?',
		signin: 'Sign In',
		newtovgen: 'New to VGEN?',
		signup: 'Sign up',
	},
	si: {
		emailPlaceholder: 'විද්‍යුත් තැපැල් ලිපිනය',
		passwordPlaceholder: 'මුරපදය',
		forgotpassword: 'මුරපදය අමතකද?',
		signin: 'පුරන්න',
		newtovgen: 'VGEN සඳහා අලුත්ද?',
		signup: 'ලියාපදිංචි වන්න',
	},
	ta: {
		emailPlaceholder: 'மின்னஞ்சல்',
		passwordPlaceholder: 'கடவுச்சொல்',
		forgotpassword: 'கடவுச்சொல்லை மறந்து?',
		signin: 'உள்நுழைக',
		newtovgen: 'VGEN க்கு புதியது?',
		signup: 'பதிவு செய்யவும்',
	},
};
const signup = {
	en: {
		firstname: 'First name',
		lastname: 'Last name',
		nic: 'NIC',
		contactno: 'Contact no',
		email: 'Email',
		password: 'Password',
		confirmpassword: 'Confirm password',
		picklocation: 'Pick location',
		currentlocation: 'Fetching current location...',
		fetchedlocation: 'Current location fetched',
		fetchedlocation2: 'Location fetched',
		customer: 'Customer',
		delivery: 'Delivery',
		signup: 'Sign Up',
		alreadyamember: 'Already a member?',
		signin: 'Sign in',
		locale: 'English',
	},
	si: {
		firstname: 'මුල් නම ',
		lastname: 'වාසගම',
		nic: 'ජා.හැ.අංකය ',
		contactno: 'දුරකථන අංකය ',
		email: 'විද්‍යුත් තැපැල් ලිපිනය',
		password: 'මුරපදය',
		confirmpassword: 'මුරපදය තහවුරු කරන්න ',
		picklocation: 'ලිපිනයක් තෝරන්න',
		currentlocation: 'වර්තමාන ලිපිනය ලබාගනිමින් පවතී...',
		fetchedlocation: 'වත්මන් ලිපිනය ලබා ගන්නා ලදී',
		fetchedlocation2: 'ලිපිනය ලබා ගන්නා ලදී',
		customer: 'පාරිභෝගික',
		delivery: 'බෙදාහැරීම්',
		signup: 'ලියාපදිංචි වන්න ',
		alreadyamember: 'දැනටමත් සාමාජිකයෙක්ද?',
		signin: 'පුරන්න',
		locale: 'සිංහල',
	},
	ta: {
		firstname: 'முதல் பெயர்',
		lastname: 'கடைசி பெயர்',
		nic: 'தேசிய அடையாள அட்டை',
		contactno: 'தொடர்பு எண்',
		email: 'மின்னஞ்சல்',
		password: 'கடவுச்சொல்',
		confirmpassword: 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
		picklocation: 'ஒரு இடத்தை தேர்வு செய்யவும்',
		currentlocation: 'தற்போதைய இருப்பிடத்தைப் பெறுகிறது...',
		fetchedlocation: 'தற்போதைய இடம் பெறப்பட்டது',
		fetchedlocation2: 'இடம் பெறப்பட்டது',
		customer: 'வாடிக்கையாளர்',
		delivery: 'டெலிவரி ரைடர்',
		signup: 'பதிவு செய்யவும்',
		alreadyamember: 'ஏற்கனவே உறுப்பினர்?',
		signin: 'உள்நுழைக',
		locale: 'தமிழ்',
	},
};
const createcommunity = {
	en: {
		firstname: 'First name',
		lastname: 'Last name',
		nic: 'NIC',
		contactno: 'Contact no',
		email: 'Email',
		password: 'Password',
		confirmpassword: 'Confirm password',
		picklocation: 'Pick location',
		currentlocation: 'Fetching current location...',
		fetchedlocation: 'Current location fetched',
		fetchedlocation2: 'Location fetched',
		customer: 'Customer',
		delivery: 'Delivery',
		signup: 'Sign Up',
		alreadyamember: 'Already a member?',
		signin: 'Sign in',
		locale: 'English',
	},
	si: {
		firstname: 'මුල් නම ',
		lastname: 'වාසගම',
		nic: 'ජා.හැ.අංකය ',
		contactno: 'දුරකථන අංකය ',
		email: 'විද්‍යුත් තැපැල් ලිපිනය',
		password: 'මුරපදය',
		confirmpassword: 'මුරපදය තහවුරු කරන්න ',
		picklocation: 'ලිපිනයක් තෝරන්න',
		currentlocation: 'වර්තමාන ලිපිනය ලබාගනිමින් පවතී...',
		fetchedlocation: 'වත්මන් ලිපිනය ලබා ගන්නා ලදී',
		fetchedlocation2: 'ලිපිනය ලබා ගන්නා ලදී',
		customer: 'පාරිභෝගික',
		delivery: 'බෙදාහැරීම්',
		signup: 'ලියාපදිංචි වන්න ',
		alreadyamember: 'දැනටමත් සාමාජිකයෙක්ද?',
		signin: 'පුරන්න',
		locale: 'සිංහල',
	},
	ta: {
		firstname: 'முதல் பெயர்',
		lastname: 'கடைசி பெயர்',
		nic: 'தேசிய அடையாள அட்டை',
		contactno: 'தொடர்பு எண்',
		email: 'மின்னஞ்சல்',
		password: 'கடவுச்சொல்',
		confirmpassword: 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
		picklocation: 'ஒரு இடத்தை தேர்வு செய்யவும்',
		currentlocation: 'தற்போதைய இருப்பிடத்தைப் பெறுகிறது...',
		fetchedlocation: 'தற்போதைய இடம் பெறப்பட்டது',
		fetchedlocation2: 'இடம் பெறப்பட்டது',
		customer: 'வாடிக்கையாளர்',
		delivery: 'டெலிவரி ரைடர்',
		signup: 'பதிவு செய்யவும்',
		alreadyamember: 'ஏற்கனவே உறுப்பினர்?',
		signin: 'உள்நுழைக',
		locale: 'தமிழ்',
	},
};
const menu = {
	en: {
		profile: 'Update profile',
		locale: 'English',
		changelanguage: 'Change language',
		createcommunity: 'Create community',
	},
	si: {
		profile: 'ගිණුම යාවත්කාලීන කරන්න',
		locale: 'සිංහල',
		changelanguage: 'භාෂාව වෙනස් කරන්න',
		createcommunity: 'නව සමුහයක් සාදන්න',
	},
	ta: {
		profile: 'சுயவிவரத்தைப் புதுப்பிக்கவும்',
		locale: 'தமிழ்',
		changelanguage: 'மொழியை மாற்றவும்',
		createcommunity: 'சமூகத்தை உருவாக்குங்கள்',
	},
};
const updateprofile = {
	en: {
		title: 'Update profile',
		chooseimage: 'New profile picture ',
		contactno: 'Contact no',
		newpassword: 'New password',
		confirmnewpassword: 'Confirm new password',
		btntitle: 'Update',
	},
	si: {
		title: 'ගිණුම යාවත්කාලීන කරන්න',
		chooseimage: 'පැතිකඩ පින්තූරය',
		contactno: 'දුරකථන අංකය',
		newpassword: 'නව මුරපදය',
		confirmnewpassword: 'නව මුරපදය තහවුරු කරන්න',
		btntitle: 'යාවත්කාලීන කරන්න',
	},
	ta: {
		title: 'சுயவிவரத்தைப் புதுப்பிக்கவும்',
		chooseimage: 'சுயவிவர படம்',
		contactno: 'தொடர்பு எண்',
		newpassword: 'புதிய கடவுச்சொல்',
		confirmnewpassword: 'புதிய கடவு சொல்லை உறுதி செய்',
		btntitle: 'மேம்படுத்தல்',
	},
};
export {signin, signup, menu, updateprofile};
